// LISTAS DA EQUIPA COMERCIAL (Fácil de editar!)
// Para adicionar um novo funcionário, basta adicionar o nome entre aspas e colocar uma vírgula no final.

export const LISTA_CONSULTORES = [
  "ANDRE RICHARDS OLIVEIRA DE LIMA",
  "BRENA KESIA DA SILVA SOUSA DA COSTA",
  "BRENO CESAR DE OLIVEIRA LEMOS",
  "EDUARDA VANESSA FRANCA DA SILVA",
  "GISLANDIA CARLA DE ASSIS",
  "HELOISA DEVENUTO MARINHO",
  "JOICE VANESSA DA SILVA DE LIMA",
  "RAILSON ALBERTO ARAUJO DE QUEIROZ",
  "THIAGO FERREIRA DE ALMEIDA",
  "WOLNEI DE OLIVEIRA REIS",
  "LEVI DOS SANTOS SILVA",
  "EDUARDO DE CARVALHO A. BARROS",
];

export const LISTA_FECHADORES = [
  "BRENA KESIA DA SILVA SOUSA",
  "BRENO CESAR DE OLIVEIRA LEMOS",
  "DIONE CORTINAZ",
  "JANEIDE CRISTINA ARAUJO DOS SANTOS",
  "LEVI DOS SANTOS SILVA",
  "RAILSON ALBERTO ARAUJO DE QUEIROZ",
  "REGINA COSTA CHAGAS SASSO",
  "ROMULO COSME ABREU DO NASCIMENTO",
  "THIAGO FARIAS PEREIRA DE LIMA",
  "THIAGO FERREIRA DE ALMEIDA",
  "WOLNEI DE OLIVEIRA REIS",
  "EDUARDO DE CARVALHO A. BARROS",
  "HELOISA DEVENUTO MARINHO",
];

export const LISTA_CAPTADORES = [
  "ALEXANDRE OLIVEIRA DO NASCIMENTO",
  "DANIEL DA SILVA VILELA",
  "ELIFABIO FERNANDES DE CARVALHO",
  "EMILLY KAMILLY FERREIRA DA PAZ",
  "JOAO VICTOR VARELA DA SILVA",
  "JULIA RAFAELA ALVES DE MEDEIROS",
  "MATEUS DOS SANTOS PEREIRA",
  "MERCIA CLEIDIANE DA SILVA",
  "OZIEL MARQUES DA COSTA",
  "THIAGO FARIAS PEREIRA DE LIMA",
  "ADRIAN ALEXANDRE SOUZA SANTOS",
  "EDSON DA CONCEICAO PEREIRA",
  "EDUARDA LACERDA CARDOSO",
  "GABRIELE FRANCA DA ROCHA",
  "IASMIN SACRAMENTO DE ARAUJO GOMES",
  "IVISSON ROCHA CARMO",
  "JORDEVAL DE DEUS SANTOS JUNIOR",
  "MARINALDA ANDRADE DE LIMA",
  "YURI COSTA DE JESUS",
  "MICHELE DE SOUZA NUNES",
  "KALLISSON MAX DA SILVA",
  "GUILHERME FERREIRA MARTINS",
  "UBIRATAN ASSIS DE BRITO",
];
